# Generated by Django 2.1.3 on 2018-11-23 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketon', '0002_cinema_movie_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cinema_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketon.Cinema'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='movie_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketon.Movie'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.DateField(),
        ),
    ]
