# Generated by Django 2.1.3 on 2018-11-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketon', '0004_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='film',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='cinema_name',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='tickets',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketon.Schedule'),
        ),
    ]
