# Generated by Django 2.1.3 on 2018-11-23 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketon', '0005_auto_20181123_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketon.User'),
        ),
    ]
